### ISSUE TITLE
Refatorar os diálogos: Medição da gravidade do Risco

### ISSUE THREAD

**Issue by rafaelflarrn** [fga-eps-mds/2019.2-GloriaBot#128]
## Descrição da Issue

Melhoria no fluxo de conversa e concertar os bugs presentes nos diálogos

### Tasks

- [x] Melhorar diálogo
- [x] Acertar os esquemas entre conversas

### Critérios de aceitação

- [x] Deixar a conversa mais fluida
- [x] Concertar os bugs presente no fluxo da conversa
