### ISSUE TITLE
Refatorar os diálogos: Caso a vítima tenha tentado deixar o agressor

### ISSUE THREAD

**Issue by GabrielHussein** [fga-eps-mds/2019.2-GloriaBot#132]
## Descrição da Issue

Melhoria no fluxo de conversa e consertar os bugs presentes nos diálogos

### Tasks

- [x] Melhorar diálogo
- [ ] Acertar os esquemas entre conversas

### Critérios de aceitação

- [ ] Deixar a conversa mais fluida
- [ ] Consertar os bugs presente no fluxo da conversa
