### ISSUE TITLE
Refatorar os diálogos: Caso o agressor tenha ameaçado os filhos da vítima

### ISSUE THREAD

**Issue by GabrielHussein** [fga-eps-mds/2019.2-GloriaBot#134]
## Descrição da Issue

Melhoria no fluxo de conversa e consertar os bugs presentes nos diálogos

### Tasks

- [ ] Melhorar diálogo
- [ ] Acertar os esquemas entre conversas

### Critérios de aceitação

- [ ] Deixar a conversa mais fluida
- [ ] Consertar os bugs presente no fluxo da conversa
