### ISSUE TITLE
Refatorar os diálogos: Caso o agressor tenha algum recurso para encontrar a vítima se ela o deixar

### ISSUE THREAD

**Issue by GabrielHussein** [fga-eps-mds/2019.2-GloriaBot#135]
## Descrição da Issue

Melhoria no fluxo de conversa e consertar os bugs presentes nos diálogos

### Tasks

- [x] Melhorar diálogo
- [x] Acertar os esquemas entre conversas

### Critérios de aceitação

- [x] Deixar a conversa mais fluida
- [x] Consertar os bugs presente no fluxo da conversa
