### ISSUE TITLE
Refatorar diálogo - Caso o agressor tenha pensamentos suicidas

### ISSUE THREAD

**Issue by VictorAmaralC** [fga-eps-mds/2019.2-GloriaBot#137]
## Descrição da Issue

Melhoria no fluxo de conversa e consertar os bugs presentes nos diálogos

### Tasks

- [ ] Melhorar diálogo
- [ ] Acertar os esquemas entre conversas

### Critérios de aceitação

- [ ] Deixar a conversa mais fluida
- [ ] Consertar os bugs presente no fluxo da conversa
