### ISSUE TITLE
Mudanças das intents

### ISSUE THREAD

**Issue by rafaelflarrn** [fga-eps-mds/2019.2-GloriaBot#145]
### Descrição

Melhoria das intentes do bot

## Tasks

- [x] Criar novas intents
- [x] Atualizar intents existentes

## Critérios de aceitação

- [x] Bot funcional com a atualização das intents
