### ISSUE TITLE
Melhoria da Issue Template

### ISSUE THREAD

**Issue by rafaelflarrn** [fga-eps-mds/2019.2-GloriaBot#51]
## Descrição da Issue

Nessa issue deve ser realizada a melhoria do template das Issues. O template deve conter uma descrição detelhada de como criar cada tipo de issue usada no projeto.

### Tasks

- [x] Feature request issue
- [x] User-Story issue
- [x] Bug report issue
