### ISSUE TITLE
Melhor interligação entre diálogos

### ISSUE THREAD

**Issue by rafaelflarrn** [fga-eps-mds/2019.2-GloriaBot#91]
### Descrição da issue:

Melhorar a ligação entre os diálogos para tornar a conversa mais natural.

#### Tasks

- [x] Criar uma forma da Glória conseguir conduzir a conversa de maneira fluida.
- [x] Ligar tópicos diferentes

#### Critérios de aceitação

- [x] Tornar a conversa mais agradável
- [x] Tornar a conversa aparentemente diversificada
