### ISSUE TITLE
HOTFIX Branch

### ISSUE THREAD

**Issue by rafaelflarrn** [fga-eps-mds/2019.2-GloriaBot#94]
## Descrição da Issue

Mudanças dos links dos arquivos de contribuição e de código de conduta. Remoção de check points.

### Tasks

- [x] Colocar os links corretos
- [x] Remover os check points

### Critérios de aceitação

- [x] Links para os domínios corretos
- [x] Funcionamento correto do sistema de check point
